#!/usr/bin/env python3
import argparse
import os
import sys
import time
import traceback

from ps.detector import DetectorRegistry
from ps.files import Directory, FileDescriptorManager
import ps.display
import ps.logging
import config

def parse_args():
    parser = argparse.ArgumentParser(prog='project-status', description="Manage your projects.")
    parser.add_argument("--disable-formatting", help="disable output formatting", action="store_true")
    parser.add_argument("--no-open", help="don't open files (for performance)", action="store_true")
    parser.add_argument("--verbose", "-v", help="print what is done", action="store_true")
    
    subparsers = parser.add_subparsers(help="command", dest="command", required=True)
    
    # build-system
    sp_build_system = subparsers.add_parser("build-system", help="configure, build or run targets")
    sp_build_system.add_argument("subcommand", nargs="?", help="build system command", default=".", choices=["run","configure","build","clean","info"])
    sp_build_system.add_argument("path", nargs="?", help="path to display", default=".")
    sp_build_system.add_argument("--build-system", help="specify build system to use")
    sp_build_system.add_argument("--exclude", "-x", help="exclude specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    sp_build_system.add_argument("--include", "-i", help="include only specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    sp_build_system.add_argument("args", nargs="*", help="args to pass to build system", default="")
    
    # display-tree
    sp_display_tree = subparsers.add_parser("display-tree", help="display filesystem tree with guesses")
    sp_display_tree.add_argument("path", nargs="?", help="path to display", default=".")
    sp_display_tree.add_argument("--exclude", "-x", help="exclude specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    sp_display_tree.add_argument("--include", "-i", help="include only specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    
    # config
    sp_config = subparsers.add_parser("config", help="get/set various config options")
    sp_config.add_argument("name", help="Config option name", choices=["guessers"])
    sp_config.add_argument("--more", "-m", help="print more detailed information", action="store_true")
    
    # info
    sp_info = subparsers.add_parser("info", help="display info in fancy way")
    sp_info.add_argument("path", nargs="?", help="path to list projects from", default=".")
    sp_info.add_argument("--exclude", "-x", help="exclude specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    sp_info.add_argument("--include", "-i", help="include only specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    
    # list
    sp_list = subparsers.add_parser("list", help="list projects in directory")
    sp_list.add_argument("path", nargs="?", help="path to list projects from", default=".")
    sp_list.add_argument("--exclude", "-x", help="exclude specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    sp_list.add_argument("--include", "-i", help="include only specified files by glob (guessers if started with '/', multiple-entries shall be comma-separated)")
    
    # list-files
    sp_list_files = subparsers.add_parser("list-files", help="list files in project")
    sp_list_files.add_argument("path", nargs="?", help="path to list projects from", default=".")
    sp_list_files.add_argument("--exclude", "-x", help="exclude specified files by glob (guessers if started with '/'), comma-separated")
    sp_list_files.add_argument("--include", "-i", help="include only specified files by glob (guessers if started with '/'), comma-separated")
    sp_list_files.add_argument("--guesses", "-g", help="specify guess types to list, comma separated", required=True)
    
    # project-log
    sp_project_log = subparsers.add_parser("project-log", help="generate project log basing on version control data")
    sp_project_log.add_argument("path", nargs="?", help="path to project", default=".")
    sp_project_log.add_argument("--version-control", help="specify version control to use")
    # TODO: Support custom formats
    sp_project_log.add_argument("--format", "-f", help="specify format", choices=["default","compact","no-version"], default="default")
    
    # version
    sp_version = subparsers.add_parser("version", help="display version and quit")

    return parser.parse_args()

def setup_directory():
    config.args.exclude = config.args.exclude.split(",") if config.args.exclude != None else []
    config.args.include = config.args.include.split(",") if config.args.include != None else []
    
    print("Setting up directory listing")
    return Directory(None, config.args.path)

def do_run_commands():
    if config.args.command == "build-system":
        file_list = setup_directory()
        ps.logging.print_status("", "")
        print("Generating output")
        file_list.run_build_command(config.args.build_system, config.args.subcommand)
    
    elif config.args.command == "display-tree":
        file_list = setup_directory()
        ps.logging.print_status("", "")
        print("Generating output")
        print(file_list)

    elif config.args.command == "info":
        file_list = setup_directory()
        ps.logging.print_status("", "")
        print("Generating output")
        ps.display.directory_fancy_display(file_list)

    elif config.args.command == "list":
        file_list = setup_directory()
        ps.logging.print_status("", "")
        print("Generating output")
        file_list.print_projects()

    elif config.args.command == "list-files":
        file_list = setup_directory()
        ps.logging.print_status("", "")
        print("Generating output")
        file_list.print_if_has_guesses(config.args.guesses.split(","))
        
    elif config.args.command == "project-log":
        config.args.exclude = []
        config.args.include = []
        file_list = Directory(None, config.args.path, max_depth=1)
        ps.logging.print_status("", "")
        print("Generating output")
        file_list.print_project_log_for_guess(config.args.version_control, config.args.format)

def main(args):
    if args.command == "version":
        print("Project Status v1.0\nCopyright (c) Sppmacd 2021")
        sys.exit(0)
    elif args.command == "config":
        if args.name == "guessers":
            for priority, guesser_list in DetectorRegistry.instance.file_type_guessers.items():
                print(ps.logging.sgr("1;33", "priority") + " = " + ps.logging.sgr("35", str(priority)) + ": ")
                for guesser in guesser_list:
                    print(" • " + ps.logging.sgr("32", "/" + guesser.name), end="")
                    if args.more:
                        guesser.print_additional_info()
                    print()
                print()
        sys.exit(0)
    
    config.args = args
    
    FileDescriptorManager()
    do_run_commands()

try:
    if __name__ == "__main__":
        main(parse_args())
    else:
        ps.logging.print_error("Importing as module not supported!")
except KeyboardInterrupt:
    ps.logging.print_error("Interrupted :(")
except SystemExit:
    pass
except:
    print("Exception :( " + str(sys.exc_info()))
    traceback.print_exc()
